apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-Deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        apps: nginx
    spec: 
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports: 
        - containerPort: 80